name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    name: cargo build
    strategy:
      matrix:
        os: [ubuntu, macos]
        toolchain: ["nightly"]
        include:
          - os: ubuntu
            toolchain: 1.72.0
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build --all-targets

  publish:
    name: cargo publish
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/main')
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: [build]
    environment: crates-io
    steps:
      - uses: actions/checkout@v5
      - run: cargo generate-lockfile && cat Cargo.lock
      - run: cargo publish --dry-run
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
        if: startsWith(github.ref, 'refs/tags/v')
      - run: cargo publish --no-verify --locked
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
